### ISSUE TITLE
Is this a problem with the image itself or with the code?

### ISSUE THREAD

**Issue by zwq11** [ptran1203/pytorch-animeGAN#12]
Init models.. .
Compute mean (R,G，B)from 1792 images100%|[
Mean(B，G， R)of Hayao are [-4.4346958-8.6659159713.10061177]Dataset: real 9 style 1792,smooth 1793
Epoch 0/100
O%|
Traceback (most recent call last):
File "train. py"， line 247,in <module>
main(args)
File "train. py"，line 162,in mainfor img,*_ in bar:
File "/root/miniconda3/envs/AGAN/lib/python3.8/site-packages/tqdm/
/ tadm. py"，line 919,in __iter_
for obj in iterable:
File"/root/miniconda3/envs/AGAV/1ib/python3.8/site-packages/torch/utils/data/dataloader.py"，line 517，in_nextdata = self._next_data()
File "/root/minicandla3/envs/AGNV1ib/python3.8/site packages/torch/utils/data/dataloader. py"，line 1199，in _next_datareturn self. _process_data(data)
File "/rot/minicomda83/envs /ACGNV/lib/python3.8/site-packages/torch/utils/data/dataloader.py"，line 1225,in _process_datadata.reraise()
File "/root/miniconda3/envs/AGAV/1ib/python3.8/site packages/torch/_utils.py"，line 429,in reraiseraise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.Original Traceback (most recent call last):
File "/root/miniconda3/envs/AGNV1ib/python3.8/site-packages/torch/utils/data/l_utils/worker.py"，line 202,in _worker_loopdata = fetcher.fetch(index)
File"/root/miniconda3/envs/AGAV1ib/python3.8/site packages/torch/utils/data/_utils/fetch. py"，line 44，in fetchdata = [self.dataset[idx] for idx in possibly_batched_index]
File "/root/miniconda3/envs/AGAV/1ib/python3.8/site packages/torch/uti1s/data/_utils/fetch.py"， line 44，in <listcomp>data = [self.dataset[idx] for idx in possibly_batched_index]
File "/root/autodl-tmp/pytorch-animeGAN-master/dataset.py"，line 67,in _getitemimage = self.load photo(index)
File "/root/autodl-tmp/pytorch-animeGAN-master/dataset.py"，line 79, in load photoimage = cv2.imread(fpath)[:,:,::-1]
TypeError: 'NoneType’object is not subscriptable

**Comment by ptran1203** [comment]
TypeError: 'NoneType’object is not subscriptable

This error indicate that image is None, probably you want to check the image path

**Comment by zwq11** [comment]
Already checked the path, can not adjust the problem, there is a better way to solve？

**Comment by ptran1203** [comment]
```python
image = cv2.imread(fpath)
assert image is not None, f"{fpath}, {os.path.isfile(fpath)}"
image = image[:,:,::-1]
```

Use this code to make sure you load image correctly

**Comment by zwq11** [comment]
Traceback (most recent call last):
  File "train.py", line 248, in <module>
    main(args)
  File "train.py", line 163, in main
    for img, *_ in bar:
  File "/root/miniconda3/envs/AGAN/lib/python3.8/site-packages/tqdm/_tqdm.py", line 919, in __iter__
    for obj in iterable:
  File "/root/miniconda3/envs/AGAN/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/AGAN/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/AGAN/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/AGAN/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 8.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/AGAN/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/AGAN/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/AGAN/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/pytorch-animeGAN-master/dataset.py", line 69, in __getitem__
    image = self.load_photo(index)
  File "/root/autodl-tmp/pytorch-animeGAN-master/dataset.py", line 83, in load_photo
    assert image is not None, f"{fpath}, {os.path.isfile(fpath)}"
AssertionError: content/dataset/train_photo/.ipynb_checkpoints, False### The output looks like this, how do I load the image out?

**Comment by zwq11** [comment]
Already solved, thank you very much
