### ISSUE TITLE
Where is the weight of the discriminator, please?

### ISSUE THREAD

**Issue by zwq11** [ptran1203/pytorch-animeGAN#8]
# ==== Train Config ==== #
dataset Hayao
data_dir /content/dataset
epochs 100
init_epochs 4
batch_size 6
checkpoint_dir {ckp_dir}
save_image_dir {save_img_dir}
gan_loss lsgan
resume GD
use_sn True
save_interval 1
debug_samples 0
lr_g 2e-05
lr_d 4e-05
init_lr 0.0001
wadvg 10.0
wadvd 10.0
wcon 1.5
wgra 3.0
wcol 30.0
d_layers 3
d_noise False
==========================
Init models...
Compute mean (R, G, B) from 1792 images
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1792/1792 [00:04<00:00, 373.49it/s]
Mean(B, G, R) of Hayao are [-4.4346958  -8.66591597 13.10061177]
Dataset: real 6656 style 1792, smooth 1792
G weight loaded
Could not load checkpoint, train from scratch [Errno 2] No such file or directory: '{ckp_dir}/discriminator_Hayao.pth'
Epoch 13/100
  0%|                                                                                                                                                                                                  | 0/1110 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 247, in <module>
    main(args)
  File "train.py", line 191, in main
    fake_img = G(img).detach()
  File "/root/miniconda3/envs/AGAN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/pytorch-animeGAN-master/modeling/anime_gan.py", line 55, in forward
    out = self.encode_blocks(x)
  File "/root/miniconda3/envs/AGAN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/AGAN/lib/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/root/miniconda3/envs/AGAN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/pytorch-animeGAN-master/modeling/conv_blocks.py", line 73, in forward
    out = self.ins_norm(out)
  File "/root/miniconda3/envs/AGAN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/AGAN/lib/python3.6/site-packages/torch/nn/modules/instancenorm.py", line 59, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/root/miniconda3/envs/AGAN/lib/python3.6/site-packages/torch/nn/functional.py", line 2183, in instance_norm
    input, weight, bias, running_mean, running_var, use_input_stats, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by ptran1203** [comment]
the error is not about discriminator weight, please check again your path, the actually error is

> RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by zwq11** [comment]
I understand, thank you very much!

**Comment by zwq11** [comment]
FileNotFoundError: Dataset not found /content/dataset/Kimetsu

Is there a problem with the file path in this case?
